name: Deploy Fullstack App (Angular + Laravel)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # --------- Build Angular ----------
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Angular dependencies
        working-directory: frontend
        run: npm install

      - name: Build Angular app
        working-directory: frontend
        run: npm run build -- --configuration production

      # --------- Deploy Angular to cPanel ----------
      - name: Deploy Angular via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: frontend/dist/mon-app/
          server-dir: public_html/barhamienne/   # Modifié pour déployer dans un sous-dossier

      # --------- Deploy Laravel backend ----------
      - name: Deploy Laravel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: backend/
          server-dir: public_html/barhamienne/   # Modifié pour déployer dans un sous-dossier
